### ISSUE TITLE
Section 4.5.6: Value for speed for stationary device

### ISSUE THREAD

**Issue by magnus-git** [w3c/geolocation-api#55]
In Section 4.5.5, it is stated that a stationary hosting device should return NaN for heading. Shouldn't the same be true for the speed attribute returned by a stationary hosting device in Section 4.5.6? This could be a way of differentiating between a stationary device and a hosting device that temporarily has no speed (or heading).

**Comment by reillyeon** [comment]
The speed of a stationary device is `0` while the speed of a device which cannot detect it's speed is `null`. A stationary device returns `NaN` for the heading because heading is undefined for a device which is not moving. Implementation typically do not have the ability to detect that a device is incapable of moving.

**Comment by samuelweiler** [comment]
This makes sense to me.  Tagging for tracking purposes, but closing.
