### ISSUE TITLE
I can't find step 6?

### ISSUE THREAD

**Issue by Alastair-L** [w3c/geolocation-api#60]
![image](https://user-images.githubusercontent.com/32168886/94089658-10760000-fe57-11ea-9ef1-4d786faaaf58.png)
In the docs here: https://www.w3.org/TR/geolocation-API/

**Comment by anssiko** [comment]
Thanks for reporting this issue. This spec bug has been fixed in the latest Editor’s Draft, please see https://w3c.github.io/geolocation-api/#dfn-watch-process

Publication of a new version at the URL you were looking at is work in progress. You can track progress of that action at https://github.com/w3c/geolocation-api/issues/42 and https://github.com/w3c/geolocation-api/issues/43.

**Comment by Alastair-L** [comment]
Thanks for that @anssiko.
