### ISSUE TITLE
Republish as CR

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/geolocation-api#93]
@reillyeon @anssiko @xfq, this should now be ready to go to CR. 

When possible, could you kindly please send out a CFC to the group? Happy to help with whatever process things are needed.

**Comment by marcoscaceres** [comment]
@anssiko, not sure if you are back from vacation, but 👋 in case you are.

**Comment by anssiko** [comment]
@marcoscaceres can you update https://w3c.github.io/geolocation-api/#changes-since-last-publication with a summary of changes since https://www.w3.org/TR/2021/WD-geolocation-20210730/ to be included in the CFC? There are a few important normative changes.

I'd probably rename the section to "Change log" and leave in "Since publication of the Second Edition in 2016" and add the delta "Since First ..." but I leave these details for you to figure out.

**Comment by marcoscaceres** [comment]
Good suggestions. Added in #102.

For the CFC.. 

Since First Public Working Draft in 2021, the Geolocation API has received the following normative changes:

* Return 0 when watchPosition() errors (#100)
* Callback with error if doc is not fully active (#97)
* Gracefully handle documents that are not fully active (#90)
* Add "geolocation task queue" (#87)

**Comment by marcoscaceres** [comment]
Transition request:
https://github.com/w3c/transitions/issues/373

**Comment by marcoscaceres** [comment]
closing as duplicate of w3c/transitions#373
